import type { Startup } from "@/lib/types";

export const categories = [
  "Fintech",
  "SaaS",
  "D2C",
  "AI",
  "Healthtech",
  "Edtech",
  "Creator Tools",
  "B2B Services"
];

export const seedStartups: Startup[] = [
  {
    id: "seed-1",
    slug: "ledgerloop",
    name: "LedgerLoop",
    founderName: "Ananya Rao",
    founderEmail: "ananya@ledgerloop.in",
    website: "https://ledgerloop.in",
    tagline: "Revenue reconciliation for modern finance teams.",
    description: "LedgerLoop helps Indian SaaS and marketplace companies reconcile payment gateway, bank, and GST data in one clean workflow.",
    category: "Fintech",
    country: "India",
    city: "Bengaluru",
    pricingModel: "Subscription",
    listingType: "directory",
    askingPrice: null,
    revenue30d: 1840000,
    mrr: 1620000,
    growthPercent: 18,
    verificationStatus: "verified",
    proofUpdatedAt: "2026-04-10",
    logo: "LL",
    featured: true,
    approved: true,
    rejected: false,
    createdAt: "2026-02-11",
    updatedAt: "2026-04-10",
    socials: { x: "https://x.com", linkedin: "https://linkedin.com" }
  },
  {
    id: "seed-2",
    slug: "kartpilot",
    name: "KartPilot",
    founderName: "Raghav Menon",
    founderEmail: "raghav@kartpilot.co",
    website: "https://kartpilot.co",
    tagline: "Checkout analytics for D2C growth teams.",
    description: "KartPilot gives D2C brands a clean view of checkout drop-offs, COD risk, repeat purchases, and revenue cohorts.",
    category: "D2C",
    country: "India",
    city: "Mumbai",
    pricingModel: "Usage based",
    listingType: "for_sale",
    askingPrice: 6500000,
    revenue30d: 1265000,
    mrr: 1090000,
    growthPercent: 12,
    verificationStatus: "proof_uploaded",
    proofUpdatedAt: "2026-04-07",
    logo: "KP",
    featured: true,
    approved: true,
    rejected: false,
    createdAt: "2026-01-24",
    updatedAt: "2026-04-07"
  },
  {
    id: "seed-3",
    slug: "caregrid",
    name: "CareGrid",
    founderName: "Meera Iyer",
    website: "https://caregrid.health",
    tagline: "Patient follow-up automation for clinics.",
    description: "CareGrid automates appointment nudges, post-visit follow-ups, and patient education for neighborhood clinics.",
    category: "Healthtech",
    country: "India",
    city: "Chennai",
    pricingModel: "Per clinic",
    listingType: "directory",
    askingPrice: null,
    revenue30d: 890000,
    mrr: 810000,
    growthPercent: 9,
    verificationStatus: "verified",
    proofUpdatedAt: "2026-03-28",
    logo: "CG",
    featured: false,
    approved: true,
    rejected: false,
    createdAt: "2026-01-09",
    updatedAt: "2026-03-28"
  },
  {
    id: "seed-4",
    slug: "pitchdesk-ai",
    name: "PitchDesk AI",
    founderName: "Kabir Sharma",
    website: "https://pitchdesk.ai",
    tagline: "Investor-ready decks from raw founder notes.",
    description: "PitchDesk AI helps founders convert traction, metrics, and product context into sharp fundraising narratives.",
    category: "AI",
    country: "India",
    city: "Delhi",
    pricingModel: "Freemium",
    listingType: "for_sale",
    askingPrice: 3200000,
    revenue30d: 742000,
    mrr: 680000,
    growthPercent: 32,
    verificationStatus: "proof_uploaded",
    proofUpdatedAt: "2026-04-02",
    logo: "PD",
    featured: false,
    approved: true,
    rejected: false,
    createdAt: "2026-02-04",
    updatedAt: "2026-04-02"
  },
  {
    id: "seed-5",
    slug: "skillnest",
    name: "SkillNest",
    founderName: "Pooja Nair",
    website: "https://skillnest.in",
    tagline: "Cohort operations for micro-learning brands.",
    description: "SkillNest powers admissions, batches, payments, and completion certificates for independent educators.",
    category: "Edtech",
    country: "India",
    city: "Pune",
    pricingModel: "Subscription",
    listingType: "directory",
    askingPrice: null,
    revenue30d: 615000,
    mrr: 530000,
    growthPercent: 7,
    verificationStatus: "unverified",
    logo: "SN",
    featured: false,
    approved: true,
    rejected: false,
    createdAt: "2026-03-14",
    updatedAt: "2026-03-14"
  },
  {
    id: "seed-6",
    slug: "hirepulse",
    name: "HirePulse",
    founderName: "Nikhil Jain",
    website: "https://hirepulse.co",
    tagline: "Hiring pipeline intelligence for seed-stage teams.",
    description: "HirePulse keeps recruiting teams honest with pipeline health, interview quality, and offer conversion metrics.",
    category: "SaaS",
    country: "India",
    city: "Hyderabad",
    pricingModel: "Seat based",
    listingType: "wanted",
    askingPrice: 2200000,
    revenue30d: 510000,
    mrr: 480000,
    growthPercent: 15,
    verificationStatus: "verified",
    proofUpdatedAt: "2026-04-12",
    logo: "HP",
    featured: false,
    approved: true,
    rejected: false,
    createdAt: "2026-01-18",
    updatedAt: "2026-04-12"
  },
  {
    id: "seed-7",
    slug: "creatorbooks",
    name: "CreatorBooks",
    founderName: "Tara Singh",
    website: "https://creatorbooks.in",
    tagline: "Simple income tracking for creators.",
    description: "CreatorBooks helps creators track sponsorships, subscriptions, affiliate income, invoices, and tax-ready exports.",
    category: "Creator Tools",
    country: "India",
    city: "Jaipur",
    pricingModel: "Subscription",
    listingType: "for_sale",
    askingPrice: 1800000,
    revenue30d: 425000,
    mrr: 390000,
    growthPercent: 21,
    verificationStatus: "proof_uploaded",
    proofUpdatedAt: "2026-04-05",
    logo: "CB",
    featured: false,
    approved: true,
    rejected: false,
    createdAt: "2026-02-20",
    updatedAt: "2026-04-05"
  },
  {
    id: "seed-8",
    slug: "opsmith",
    name: "Opsmith",
    founderName: "Aditya Kulkarni",
    website: "https://opsmith.io",
    tagline: "Internal ops dashboards without spreadsheets.",
    description: "Opsmith gives service businesses ready-made dashboards for delivery, revenue, collections, and customer health.",
    category: "B2B Services",
    country: "India",
    city: "Ahmedabad",
    pricingModel: "Project plus retainer",
    listingType: "directory",
    askingPrice: null,
    revenue30d: 380000,
    mrr: 260000,
    growthPercent: 5,
    verificationStatus: "unverified",
    logo: "OS",
    featured: false,
    approved: true,
    rejected: false,
    createdAt: "2026-03-02",
    updatedAt: "2026-03-02"
  },
  {
    id: "seed-9",
    slug: "mintflow",
    name: "Mintflow",
    founderName: "Ishaan Verma",
    website: "https://mintflow.app",
    tagline: "Cash-flow planning for bootstrapped founders.",
    description: "Mintflow turns bank statements and invoices into practical runway, collections, and hiring forecasts.",
    category: "Fintech",
    country: "India",
    city: "Gurugram",
    pricingModel: "Subscription",
    listingType: "directory",
    askingPrice: null,
    revenue30d: 315000,
    mrr: 285000,
    growthPercent: 14,
    verificationStatus: "proof_uploaded",
    proofUpdatedAt: "2026-03-31",
    logo: "MF",
    featured: false,
    approved: true,
    rejected: false,
    createdAt: "2026-02-28",
    updatedAt: "2026-03-31"
  },
  {
    id: "seed-10",
    slug: "founderkit",
    name: "FounderKit",
    founderName: "Sara D'Souza",
    website: "https://founderkit.co",
    tagline: "Templates, metrics, and workflows for first-time founders.",
    description: "FounderKit gives early teams operating templates for investor updates, hiring, revenue tracking, and weekly reviews.",
    category: "SaaS",
    country: "India",
    city: "Goa",
    pricingModel: "One-time plus subscription",
    listingType: "for_sale",
    askingPrice: 950000,
    revenue30d: 205000,
    mrr: 140000,
    growthPercent: 26,
    verificationStatus: "unverified",
    logo: "FK",
    featured: false,
    approved: true,
    rejected: false,
    createdAt: "2026-03-22",
    updatedAt: "2026-03-22"
  }
];
